### ISSUE TITLE
0.3 upgrade?

### ISSUE THREAD

**Issue by snawbel** [d-pac/restful-keystone#1]
Hi, how is the 0.3.x upgrade going? :)

Need help? What needs to be done?

**Comment by creynders** [comment]
@snawbel Haven't had time to look into it yet. Been too busy with keystone core development :)
I think it should be very trivial to update, and maybe it even works out of the box, but I'm not sure.
Feel free to tackle this if you want!

**Comment by jasonwbsg** [comment]
I forked and changed the keystone peerDep to test against 0.3.4.  The only issue I have found so far is a couple of deprecated Express API's which I changed and it seems to be running just fine with the limited set of models in my app.

**Comment by jorgenskogmo** [comment]
+1

**Comment by creynders** [comment]
Taken care of. Released v0.3.0

**Comment by snawbel** [comment]
Nice. Thanks.
